### ISSUE TITLE
Cannot connect to database

### ISSUE THREAD

**Issue by truongbnu** [aurora-is-near/partner-relayer-deploy#10]
I am trying to run partner-relayer-deploy on windows
When I run the command docker-compose up. A lot of error occured
![image](https://user-images.githubusercontent.com/74242115/150043788-ac0f5b9e-3a89-45e9-9cd7-e47711f1fa59.png)

**Comment by JonathanLogan** [comment]
The docker images provided are not directly compatible with windows. Please change the permissions of the included directories and files to be read&writeable by the default docker user.
