### ISSUE TITLE
Can't access RPC

### ISSUE THREAD

**Issue by jacobwis** [aurora-is-near/partner-relayer-deploy#11]
Hi I'm trying to set up a node using this repo, everything appears to be synced, and I'm having trouble accessing the RPC endpoint.

When I use the command `http post http://127.0.0.1:8545 jsonrpc=2.0 id=1 method=eth_blockNumber params:='[]'` I get this error:

```
http: error: ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8545): Max retries exceeded with url: 
/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f47b443ce48>: Failed to establish a
new connection: [Errno 111] Connection refused')) while doing POST request to URL: http://127.0.0.1:8545/
```

**Comment by JonathanLogan** [comment]
The rpc node will listen on a docker IP address. If docker is correctly installed you can use http://mainnet_endpoint:8545
Alteratively find out the correct IP with:

docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mainnet_endpoint
