### ISSUE TITLE
Can't send transaction

### ISSUE THREAD

**Issue by daichuanliang** [aurora-is-near/partner-relayer-deploy#12]
I have synced the latest block. The blockNum is same as https://mainnet.aurora.dev. But the tx always failed with my own RPC.
![image](https://user-images.githubusercontent.com/16792644/150738624-c036aea7-3a3b-4a42-a562-732bd6376c58.png)

**Comment by JonathanLogan** [comment]
Did you configure an account for the relayer by replacing the signer name and keypair? If not, see the keypair for
"Write transactions & custom signers"

**Comment by daichuanliang** [comment]
> 

Not yet, I just modifyed the writable flag to true. How to get the account for the relayer?

**Comment by daichuanliang** [comment]
> 

Yes. I have configured the relayer.json and mainnet.yaml by replacing the signer and keypair, and changed the wirtable to true.  But it also swaped failed. The error log is bellow.(I have deleted the rpc host from the log )
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - blacklist(...).has is not a function. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"my rpc node"}}}}'

**Comment by JonathanLogan** [comment]
Copy the file .contrib/blacklist.yaml to the config directory.
