### ISSUE TITLE
No peers and swaped failed

### ISSUE THREAD

**Issue by daichuanliang** [aurora-is-near/partner-relayer-deploy#13]
I used the guide to set up a aurora full node step by step. And I check the blocknum is same as https://mainnet.aurora.dev .
But I found 2 questions about my full node.
1. There is no peers. 
     **cmd:  curl -X POST -H 'content-type:application/json' --data '{"jsonrpc":"2.0","method":"net_peerCount","params":[],"id":1}'  127.0.0.1:18545
     result:  {"jsonrpc":"2.0","id":1,"result":"0x0"}**

2. I can't send any transaction through my full node.  I have configured the relayer.json and mainnet.yaml by replacing the signer and keypair, and changed the wirtable to true. But it also swaped failed. The error log is bellow.

[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - blacklist(...).has is not a function. Please report a bug at https://github.com/aurora-is-near/aurora-relayer/issues","data":{"host":"my rpc node"}}}}'

**Comment by daichuanliang** [comment]
Blacklist configuration file can not be loaded (Error: ENOENT: no such file or directory, open 'config/blacklist.yaml').
Blacklist configuration file can not be loaded (Error: ENOENT: no such file or directory, open 'config/blacklist.yaml').
{"level":50,"time":1643168705531,"pid":7,"hostname":"d5547a767f5d","stack":"TypeError: blacklist(...).has is not a function\n    at DatabaseServer._isBannedEOA (file:///srv/aurora/relayer/lib/servers/skeleton.js:16:34)\n    at DatabaseServer._enforceEOABan (file:///srv/aurora/relayer/lib/servers/skeleton.js:27:18)\n    at DatabaseServer._enforceBans (file:///srv/aurora/relayer/lib/servers/skeleton.js:23:14)\n    at DatabaseServer.eth_getBalance (file:///srv/aurora/relayer/lib/servers/database.js:89:14)\n    at Method.execute (file:///srv/aurora/relayer/lib/server.js:23:37)\n    at /srv/aurora/relayer/node_modules/jayson/lib/server/index.js:315:12\n    at maybeParse (/srv/aurora/relayer/node_modules/jayson/lib/server/index.js:440:5)\n    at Server.call (/srv/aurora/relayer/node_modules/jayson/lib/server/index.js:243:3)\n    at file:///srv/aurora/relayer/lib/app.js:40:16\n    at Layer.handle [as handle_request] (/srv/aurora/relayer/node_modules/express/lib/router/layer.js:95:5)","type":"Error","msg":"blacklist(...).has is not a function"}

**Comment by JonathanLogan** [comment]
Please copy the blacklist.yaml file from the .contrib directory to the config directory. That should fix it.
