### ISSUE TITLE
Question about running `./setup.sh`

### ISSUE THREAD

**Issue by nEoKLKE** [aurora-is-near/partner-relayer-deploy#16]
When I run `./setup.sh` it keeps showing like :
`Downloading near chain snapshot
Fetching... this can take some time...
1596544.sst
1602709.sst
1717744.sst
1741384.sst
2177555.sst
2199948.sst
2516545.sst
3013525.sst
3014465.sst
3014466.sst
3014467.sst
3014468.sst
3014469.sst
3014470.sst
3014471.sst
3014472.sst
3014473.sst
3014474.sst
3014475.sst
3014476.sst
3014477.sst
3014478.sst
3014479.sst
3014480.sst
3014481.sst
3014482.sst
3014483.sst
3014484.sst
3014485.sst
3014486.sst
3014487.sst
3014488.sst
3014489.sst
3014490.sst
3014491.sst`

Is that normal or I'm facing something wrong?

**Comment by nEoKLKE** [comment]
Seems like it's the normal process of running `./setup.sh`.

**Comment by JonathanLogan** [comment]
Yes, it prints all filenames that it creates. It's >250 GB in many small files to download.

**Comment by nEoKLKE** [comment]
I see, thanks for reply!
