### ISSUE TITLE
`mainnet_nearcore` sync doesnt work

### ISSUE THREAD

**Issue by nEoKLKE** [aurora-is-near/partner-relayer-deploy#17]
I have run `c2-standard-8` on GCP as the [offical recommended hardware](https://docs.near.org/docs/develop/node/validator/hardware), and setup completely with `./setup.sh`.

When I run with `nohup docker-compose up &` and see what I get later, it shows that `mainnet_nearcore` sync speed is extremely slow, and I have tried re-run it lots of times but still not work, how could I solve the problem please?

![image](https://user-images.githubusercontent.com/97164691/153742021-8e0190e1-c208-4a6d-ae62-5cd969192ddc.png)

**Comment by JonathanLogan** [comment]
Yes, this is a known issue without a clear cause.
What seems to help most is to update the nearcore docker image and re-download the near data snapshot.
