### ISSUE TITLE
Node does not catch up, bps too low

### ISSUE THREAD

**Issue by mcf-rocks** [aurora-is-near/partner-relayer-deploy#18]
To be clear, the bps is not always zero, it may be 0.10 or 0.20, but the number in (brackets) goes up - the node will NEVER catchup.

You may need to put the latests nearcore on your image, or it may be something else, don't know.
```
Feb 14 21:10:47 sdock docker-compose[3351132]: mainnet_nearcore | Feb 14 21:10:47.829  INFO stats: #59157781 Downloading blocks 99.25% (373649)  30/30/40 peers ⬇ 404.2kiB/s ⬆ 226.7kiB/s 0.00 bps 0 gas/s CPU: 13%, Mem: 6.3 GiB
```

The image is within last 24 hours, machine is 1Gbps, 32 core, 256GB ram, NVMe disks - real fast hardware.

**Comment by nEoKLKE** [comment]
Same problem here, dont know how to fix it.

**Comment by JonathanLogan** [comment]
Latest nearcore is always shipped, potentially refetch the docker images to make sure.
Apart from that the low bps is a common issue on the near network and is usually resolved by restarting the node with some pause - and re-downloading the snapshot if the gap becomes too big.

**Comment by mcf-rocks** [comment]
I will try that shortly On 17 Feb 2022 10:31, Jonathan Logan ***@***.***> wrote:
Latest nearcore is always shipped, potentially refetch the docker images to make sure.
Apart from that the low bps is a common issue on the near network and is usually resolved by restarting the node with some pause - and re-downloading the snapshot if the gap becomes too big.

**Comment by mcf-rocks** [comment]
I took it all from the top today, and it seems to all be working.
