### ISSUE TITLE
Nearcore sync speed is extreamly slow (sync rate around 1 bps)

### ISSUE THREAD

**Issue by multimint** [aurora-is-near/partner-relayer-deploy#2]
![image](https://user-images.githubusercontent.com/93041879/147375843-df520f09-ec97-46af-bb5a-d73e2d392a2e.png)

**Comment by JonathanLogan** [comment]
This depends strongly on the peer nodes to which the local node is connected, and the performance of the local node.
CPU consumption in the above log hints at the local node being not strong enough to process blocks significantly faster.

**Comment by multimint** [comment]
But according to the logs CPU is only 40% used.  Any suggestions would be appreciated.

**Comment by JonathanLogan** [comment]
Main suggestion is a restart and hope that your node connects to faster peers.

**Comment by multimint** [comment]
I restart the docker container and re-download chain snapshot many times but it still not working for me :(

**Comment by JonathanLogan** [comment]
One thing that might slightly speed up things is to ONLY start the nearcore container (not the indexer or endpoint) and let it sync.
