### ISSUE TITLE
setup.sh

### ISSUE THREAD

**Issue by mcf-rocks** [aurora-is-near/partner-relayer-deploy#21]
Gives this error over and over.
```
Fetching... this can take some time...
the input device is not a TTY
```

**Comment by JonathanLogan** [comment]
okay, your connection to GCP doesnt have a PTY opened. You can either force the connection to open a PTY, or change the line 83 of setup.sh and remove the "-ti" from the commandline.

**Comment by nEoKLKE** [comment]
> okay, your connection to GCP doesnt have a PTY opened. You can either force the connection to open a PTY, or change the line 83 of setup.sh and remove the "-ti" from the commandline.

Thanks I'm trying now.
