### ISSUE TITLE
error while running node

### ISSUE THREAD

**Issue by suyog-unmarshal** [aurora-is-near/partner-relayer-deploy#25]
hi there, trying to run aurora mainnet but docker-compose is giving error like this
docker-compose version: 1.3.1

Unsupported config option for services service: 'endpoint'

**Comment by Enigmatic331** [comment]
You might need to update your docker compose version to something more recent (https://github.com/docker/compose/releases) since the compose file is v3.

We are on v2.2.3, if it helps.
