### ISSUE TITLE
Can not sign transactions for account

### ISSUE THREAD

**Issue by damiensgit** [aurora-is-near/partner-relayer-deploy#3]
I've enabled write mode in the ./config/mainnet.yaml and am trying to send transactions using the relayer but I am getting the following error:

"Internal Error - Error: Can not sign transactions for account relayer1497898df7b5f14a.near on network mainnet, no matching key pair found in InMemorySigner(MergeKeyStore(InMemoryMultiKeyStore, InMemoryKeyStore, UnencryptedFileSystemKeyStore(/home/node/.near-credentials))).. "

I have read the various Near/Aurora docs but I'm stuck - I assume I need to use another account that Ive setup to do this ? can someone provide some clear instructions on what I need to do to allow my aurora RPC node to send txes?

**Comment by damiensgit** [comment]
I figured out my issue and how to generate my own credentials so have closed this ticket.

**Comment by multimint** [comment]
> I figured out my issue and how to generate my own credentials so have closed this ticket.

@damiensgit Cloud you provide steps to figure out this issue?

**Comment by NeoKLKE** [comment]
@damiensgit bro could you provide some guide to figure out this issue please?

**Comment by JonathanLogan** [comment]
Please see the updated readme.

**Comment by NeoKLKE** [comment]
> Please see the updated readme.

thanks a lot, it's really help!
