### ISSUE TITLE
Request: Howto Websocket & Exposing to public ip

### ISSUE THREAD

**Issue by teebaumcrypto** [aurora-is-near/partner-relayer-deploy#35]
Hi,

Currently it's only exposing to the internal ip (localhost).

How do I expose:
websocket
public ip

Which service has to be exposed?

Thank you and best regards

**Comment by silvercondor** [comment]
hi, are you able to share how you did it please

**Comment by teebaumcrypto** [comment]
@silvercondor I edited the docker-compose in the endpoint section with:
```
    ports:
      - '0.0.0.0:8545:8545'
```

Note: this will expose your whole aurora endpoint to the public, i think it's not recommended without the proper security measures

**Comment by silvercondor** [comment]
Hi, Thanks for the help, what about websocket?

**Comment by teebaumcrypto** [comment]
@silvercondor 
Websocket uses the same port afaik.
