### ISSUE TITLE
How can I modify this so it runs against my locally running node that is synced to mainnet?

### ISSUE THREAD

**Issue by keyser-nakamoto** [aurora-is-near/partner-relayer-deploy#5]
I have a near mainnet node running locally on my machine, and I want to run this script so that it uses my local Near node (and the aurora engine that is running on near mainnet). My goal is to have an aurora node running that I can query with eth_blockNumber, eth_getLogs, txpool_status, etc. without having to query against the public aurora/near RPC. I'm not sure if I'm going about this in the best way possible

**Comment by JonathanLogan** [comment]
This distribution already uses a local near node and does not use the public aurora/near RPC.

**Comment by TanyaSrivastava-Dipali** [comment]
how can i setup partner relayer with my near localnet
