### ISSUE TITLE
Cant access to json rpc endpoint

### ISSUE THREAD

**Issue by NeoKLKE** [aurora-is-near/partner-relayer-deploy#6]
I have run the node successfully step by step with the guide, but when I input `http post http://localhost:8545 jsonrpc=2.0 id=1 method=eth_blockNumber params:='[]'`, it shows `HTTPConnectionPool(host='localhost', port=8545): Max retries exceed with url: / (Caused by NewConnectionError('<urllib3.connection: [Errno 111] Connection refused',)) while doing a POST request to URL: http://localhost:8545/`. I also try `curl http://localhost:8545 -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params": [],"id":3}'`, but it doesnt work and only return error `curl: (7) Failed to connect to localhost port 8545: Connection refused`.

It seems like the local json rpc endpoint is not activated. How can I solve the problem please?

**Comment by NeoKLKE** [comment]
Problem solved.

**Comment by hollejacklin** [comment]
> Problem solved.

could you share thw solution? I also got the same issue.

**Comment by jacobwis** [comment]
Yeah it would definitely be helpful if you had posted what your solution was so others facing the same issue could reference it

**Comment by JonathanLogan** [comment]
The rpc node will listen on a docker IP address. If docker is correctly installed you can use http://mainnet_endpoint:8545
Alteratively find out the correct IP with:

docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mainnet_endpoint
