### ISSUE TITLE
Index, nearcore and endpoint containers keep restarting

### ISSUE THREAD

**Issue by Amarjeet-L** [aurora-is-near/partner-relayer-deploy#7]
hi, I followed the steps from https://github.com/aurora-is-near/partner-relayer-deploy
My setup was complete.
THe dockers got downloaded and blocks seem to be syncing in reverse order.. by the 'mainnet_resilver'
My 'mainnet_resilver' and 'mainnet_database' are up, while the other 3 containers keep restarting. The aurora-nearcode-1 shows the following logs, 
```
aurora-nearcore-1  | Jan 12 15:27:28.998  INFO neard: Version: 1.23.1, Build: 1.23.0-9-gc0551c84b-modified, Latest Protocol: 50
aurora-nearcore-1  | thread 'main' panicked at 'Failed to deserialize KeyFile: Error("EOF while parsing a value", line: 1, column: 0)', core/crypto/src/key_file.rs:37:40
aurora-nearcore-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I did not make any changes in the configs
The indexer keeps restarting with 
  ```
| Using config file: /srv/aurora/relayer/config/mainnet.yaml
mainnet_indexer  | panic: rpc call status() on http://nearcore:3030/: Post "http://nearcore:3030/": dial tcp: lookup nearcore on 127.0.0.11:53: server misbehaving
```
the endpoint container restarts with 
```
aurora-endpoint-1  | bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
aurora-endpoint-1  | {"level":30,"time":1642001530744,"pid":7,"hostname":"4de69717ba43","msg":"starting server"}
aurora-endpoint-1  | aurora-relayer: Unexpected end of JSON input
```

**Comment by JonathanLogan** [comment]
mainnet_resilver has to finish first. It's doing data/schema migration.
The nearcore issue however is a bigger problem. Can you delete the files in the near subdirectory (but not the data directory in it)?

**Comment by Amarjeet-L** [comment]
ok. Dleeting the json files.. helped . But now I have a new problem --
```
[2mJan 14 00:44:17.517[0m [32m INFO[0m neard: Version: 1.23.1, Build: 1.23.0-9-gc0551c84b-modified, Latest Protocol: 50
[2mJan 14 00:44:17.527[0m [32m INFO[0m near: Opening store database at "/home/near/data"
[2mJan 14 00:44:18.943[0m [31mERROR[0m near: DB version 31 is created by a newer version of neard, please update neard or delete data
```

should I delete the data as well and try ?

**Comment by JonathanLogan** [comment]
Bad luck, you downloaded the data during a migration run on our side. Easy to fix:
Stop the docker-compose, then:
docker image rm nearaurora/nearcore:mainnet

And try again.

**Comment by NeoKLKE** [comment]
Hello, @JonathanLogan, I have faced the same problem :

`partner-relayer-deploy-main-nearcore-1  | Jan 14 13:56:28.962 ERROR near: DB version 31 is created by a newer version of neard, please update neard or delete data
partner-relayer-deploy-main-nearcore-1 exited with code 0`

with the `mainnet_resilver` start with this message :

`mainnet_resilver                        | SKIPPED: 20211222141955 sql 20211222141955.fixnull.sql
mainnet_resilver                        | SKIPPED: 20211222141956 goose 20211222141956
mainnet_resilver                        | SKIPPED: 20211222141957 node lib/data_migrations/2021-12-14-empty-blocks.js
mainnet_resilver exited with code 0`

And I have tried your solution with deleting containers and images but it still show the same error, could you help me please?

**Comment by JonathanLogan** [comment]
The SKIPPED lines indicate that the database update was completed, so that's good. And that specific container should exit and not restart (mainnet_resilver).
For the nearcore data: If you have already updated to the latest near image (docker image rm nearaurora/nearcore:mainnet before starting compose), the only way is to delete the files in near/data/ and redownload them - please make sure to also delete the .latest file in the base directory and the .version file in the near/data directory for the download to work.

**Comment by NeoKLKE** [comment]
I see, have deleted the .latest file in the base directory and whole near/data/ directory, redownloading the them with `./setup.sh` now.

**Comment by Amarjeet-L** [comment]
I got it working thanks.. The node is up and running.
